name: publish

on: [push]

jobs:
  publish-hello-world-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the hello-world Docker image
      run: |
        echo $CR_PAT | docker login ghcr.io -u lucky1024 --password-stdin
        docker build . --tag ghcr.io/lucky1024/hello-world:latest
        docker run ghcr.io/lucky1024/hello-world:latest
        docker push ghcr.io/lucky1024/hello-world:latest
      env:
        CR_PAT: ${{ secrets.CR_PAT }}
